##########################################################################
#
#  Script: SubmitPBS.pbs
#  Note: This script is for PBSPro systems
#  Cell Ranger Version: 1.3.1
#
##########################################################################

## PBS SETTINGS
#PBS -q normal
#PBS -S /bin/bash
#PBS -r n
#PBS -l select=1:ncpus=16:mem=126GB

## ADJUSTABLE SETTINGS
#PBS -N IPSCRetina_scRNA
#PBS -l walltime=48:00:00

## Load require modules
module load bcl2fastq

# Run pipeline
source $PBS_O_WORKDIR/ProcessData.bash

## Unload modules
module unload bcl2fastq
